### ISSUE TITLE
Handle sub directories in component names

### ISSUE THREAD

**Issue by ryanlewis** [joshwcomeau/new-component#2]
You might want to use a more complex tree to handle creating components.

example:

```
src/ 
  components/
    admin/
```

You get the following error if trying to provide a path in your component name and the path does not (yet) exist.

```
ryan@tbp dev/proj (master) » new-component subdir/TestComponent


✨  Creating the subdir/TestComponent component ✨


Directory:  src/components/subdir/TestComponent
Type:       class  functional  pure-class
=========================================


{ Error: ENOENT: no such file or directory, mkdir 'src/components/subdir/TestComponent'
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'src/components/subdir/TestComponent' }
ryan@tbp dev/proj (master) »
```

... and the following error if path already exists.

```
ryan@tbp dev/proj (master) » mkdir src/components/admin
ryan@tbp dev/proj (master) » new-component admin/TestComponent


✨  Creating the admin/TestComponent component ✨


Directory:  src/components/admin/TestComponent
Type:       class  functional  pure-class
=========================================


✓ Directory created.
{ SyntaxError: Unexpected token, expected { (4:12)
  2 |
  3 |
> 4 | class admin/TestComponent extends Component {
    |            ^
  5 |   render() {
  6 |     return <div />;
  7 |   }
    at createError$1 (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/parser-babylon.js:1:112)
    at parse (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/parser-babylon.js:1:681)
    at Object.parse (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:3491:12)
    at formatWithCursor (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:13697:22)
    at format (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:13737:10)
    at Object.format (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:13945:12)
    at text (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/src/helpers.js:65:12)
    at mkDirPromise.then.then.then.then.template (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/src/index.js:100:32)
    at <anonymous>
  loc: { start: { line: 4, column: 12 } },
  codeFrame: '\u001b[0m \u001b[90m 2 | \u001b[39m\n \u001b[90m 3 | \u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 4 | \u001b[39m\u001b[36mclass\u001b[39m admin\u001b[33m/\u001b[39m\u001b[33mTestComponent\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n \u001b[90m   | \u001b[39m           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 5 | \u001b[39m  render() {\n \u001b[90m 6 | \u001b[39m    \u001b[36mreturn\u001b[39m \u001b[33m<\u001b[39m\u001b[33mdiv\u001b[39m \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 7 | \u001b[39m  }\u001b[0m' }
ryan@tbp dev/proj (master) »
```

**Comment by ryanlewis** [comment]
In addition, you might want to create a sub-component that lives in a directory for an already existing component. 

```
ryan@tbp dev/proj (master) » new-component TestComponent


✨  Creating the TestComponent component ✨


Directory:  src/components/TestComponent
Type:       class  functional  pure-class
=========================================


✓ Directory created.
✓ Component built and saved to disk.
✓ Index file built and saved to disk.


Component created! 🚀
Thanks for using new-component.


ryan@tbp dev/proj (master %) » new-component TestComponent/SubComponent


✨  Creating the TestComponent/SubComponent component ✨


Directory:  src/components/TestComponent/SubComponent
Type:       class  functional  pure-class
=========================================


✓ Directory created.
{ SyntaxError: Unexpected token, expected { (4:20)
  2 |
  3 |
> 4 | class TestComponent/SubComponent extends Component {
    |                    ^
  5 |   render() {
  6 |     return <div />;
  7 |   }
    at createError$1 (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/parser-babylon.js:1:112)
    at parse (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/parser-babylon.js:1:681)
    at Object.parse (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:3491:12)
    at formatWithCursor (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:13697:22)
    at format (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:13737:10)
    at Object.format (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/node_modules/prettier/index.js:13945:12)
    at text (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/src/helpers.js:65:12)
    at mkDirPromise.then.then.then.then.template (/Users/ryan/.nvm/versions/node/v8.2.1/lib/node_modules/new-component/src/index.js:100:32)
    at <anonymous>
  loc: { start: { line: 4, column: 20 } },
  codeFrame: '\u001b[0m \u001b[90m 2 | \u001b[39m\n \u001b[90m 3 | \u001b[39m\n\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 4 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mTestComponent\u001b[39m\u001b[33m/\u001b[39m\u001b[33mSubComponent\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\n \u001b[90m   | \u001b[39m                   \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 5 | \u001b[39m  render() {\n \u001b[90m 6 | \u001b[39m    \u001b[36mreturn\u001b[39m \u001b[33m<\u001b[39m\u001b[33mdiv\u001b[39m \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[33m;\u001b[39m\n \u001b[90m 7 | \u001b[39m  }\u001b[0m' }
ryan@tbp dev/proj (master %) »
```

**Comment by morajabi** [comment]
It looks good, but one question. For the second feature (subcomponent) should we create a directory inside the dir or just create a single JS file?

**Comment by ryanlewis** [comment]
Think some heuristics are needed here. If we detect the directory as a component folder (with an index file already) then consider the user as wanting a sub component of another component? I think that's the most likely use-case. Could always introduce a flag to override "default" behaviour.

**Comment by joshwcomeau** [comment]
Ah, yeah, good catches. My initial reasoning was to keep things as simple as possible, as it's relatively easy to move the created component directory into the new folder (in Atom, at least, I can just drag the new component dir wherever I need it). But certainly, we should handle this exception better; right now it creates a directory before exploding, and that's not good at all.

For now, I'm going to just do a patch release that catches and throws when any illegal characters (like `/`) are found in the component name. 

If anyone wants to contribute a solution for handling this usecase, though, that would be awesome :) I'm happy to continue hashing out what that solution would look like. My initial thoughts for the spec are:

Given `new-component admin/buttons/ToggleButton`:
- If `src/components/admin` doesn't exist, raise an exception
- if `src/components/admin/buttons` doesn't exist, raise an exception
- if `src/components/admin/buttons/ToggleButton` DOES exist, raise an exception.

I don't _think_ we need to do any deeper inspection (eg. to figure out whether the specified dir is a component dir or not), since I think that's an end-user concern, to make sure the path they're providing is right. Very open to be proven wrong about this though!

So yeah, TL:DR;
- Going to push out a patch soon that just adds better error-handling
- If anyone wants to tackle adding this feature, please feel free!
- We can continue discussing the spec in this issue.

**Comment by morajabi** [comment]
@joshwcomeau 

> If anyone wants to tackle adding this feature, please feel free!

I think I can give it a hand in a few days.

**Comment by joshwcomeau** [comment]
@morajabi awesome :D

> should we create a directory inside the dir or just create a single JS file because it's a subcomponent of another?

Ohh. Right, I misread that question the first time. Hadn't considered the usecase of "I have this small add-on component for this already-present component". @ryanlewis' proposal makes more sense now.

But yeah, so what I'm thinking now... I see two primary usecases for wanting to add a new component in a sub-directory:

1. You want to add a small add-on component (or maybe store several different, similar components in the same directory?)
2. You just want to organize your components into subdirectories, for organization (like the example above, about an `admin` directory that holds admin-related components).

I feel like for the first point, there are a lot of subtly different ways to manage it, and it's going to be tricky to infer intent. Maybe the user has a structure like this:

```js
components
-- admin
---|-- Button
---|-- Home
---|-- index.js
```

Maybe the `index.js` is a convenience around `Home`, to export the top Admin view... and so if we use the heuristic of looking for an `index.js`, we might do something unexpected.

The other thing I'm thinking about is ease of correcting if we get it wrong. If we add a new directory but the user just wants a single file, all they have to do is move the `Whatever.js` file up one level, and delete the `Whatever` directory. If, however, they wanted to have a directory, and we added a single file, they'd have to create a new directory with the right name, create the `index.js`, and move the file down. It feels like more trouble.

Plus, from a code complexity standpoint, I like the idea of keeping it simple. It feels simpler to have a single pattern (we always create the directory).

So yeah, for those reasons I think it's best if we go the 'create a new directory' route. Maybe there's something I haven't thought of though?

**Comment by morajabi** [comment]
> I like the idea of keeping it simple. It feels simpler to have a single pattern (we always create the directory).

Me too. I entirely agree with that.

BTW, What's exactly the reason for the directory at all?

**Comment by joshwcomeau** [comment]
> BTW, What's exactly the reason for the directory at all?

It's not uncommon for each component to need several files, like:

```
Button.js
Button.test.js
Button.helpers.js
Button.css
Button.stories.js
```

I find it pretty cluttered if they don't live in a directory together... and because of that clutter, I find it encourages me to not make those files (and so my components get bloated with the little helper methods I need, and I don't add stories or tests)

I feel like the only drawback to the directory pattern is that it adds friction when making new components, and was a big part of why I started this project :)

But yeah, I'm surprised I haven't seen more requests to have a single-file alternative, since I'm sure there are folks who disagree with me on this. I always figured if it was a super popular request I could add support, but otherwise I wouldn't bother.

**Comment by morajabi** [comment]
It's been a long time I haven't used CSS in a separate file and I write my test in a separate directory, so almost forgotten the component directory pattern :) I can see the benefit of having everything in one place, editing ease and more reusability because it's packed.

**Comment by joshwcomeau** [comment]
Ah, I meant to push out a patch release to tackle this over the weekend, but it slipped my mind. Sorry all! I'm on vacation next week so I'll definitely have some time coming up to work on this :)

> It's been a long time I haven't used CSS in a separate file and I write my test in a separate directory, so almost forgotten the component directory pattern :)

Hah, yeah, if you use css-in-js and don't colocate your tests/stories, it's not as important. I still think it's beneficial for helpers, though (this is subjective, but I like for my components to be fairly straightforward. If there's a bundle of imperative logic that isn't directly related to rendering, I like to put it in a helper method, and move that method to a helpers file)

**Comment by morajabi** [comment]
So, maybe assign it to yourself?

**Comment by joshwcomeau** [comment]
Ah geez, I shouldn't have been so confident about being able to do this! I got absorbed in an unrelated side-project.

That project is wrapping up soon, though. So I believe I'll have some bandwidth to push out a couple quick fixes for this :)

Assigning it to myself (Thanks @morajabi!) for the quick fix, but the larger issue will remain open for someone else to tackle.

**Comment by joshwcomeau** [comment]
Ah geez, I shouldn't have been so confident about being able to do this! I got absorbed in an unrelated side-project.

That project is wrapping up soon, though. So I believe I'll have some bandwidth to push out a couple quick fixes for this :)

Assigning it to myself (Thanks @morajabi!) for the quick fix, but the larger issue will remain open for someone else to tackle.

**Comment by morajabi** [comment]
Agree with *the quick fix*. I think we can keep it simple for now 👍
